# Generated by Django 4.0.4 on 2022-06-06 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_rearte', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pet',
            new_name='House_pet',
        ),
    ]
